name: Test RoboHash Gem

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick libmagickwand-dev

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Run tests
      run: bundle exec rake spec

    - name: Build and install the gem
      run: bundle exec rake install

    - name: Test the installed gem with test_installed.rb
      run: bundle exec ruby test_installed.rb

    - name: Install RMagick for image comparison
      run: gem install rmagick

    - name: Compare generated robots with reference images
      run: ruby compare_robots.rb
      continue-on-error: true

    - name: Upload generated images as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: robot-images
        path: |
          installed_robot.png
          installed_robot2.png
        retention-days: 7

    - name: Upload image differences as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: image-differences
        path: difference_*.png
        retention-days: 7
      if: ${{ always() }}  # Upload even if comparison fails